

server:
  port: 8500
  servlet:
    context-path: /${system.name}

spring:
  datasource:
    url: jdbc:mysql://agno.top:3306/db_shortage_url?useUnicode=true&amp;characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123
    name: ${system.name}
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      validation-query: select 1
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

#logging:
#  level: DEBUG
