server:
  port: 8500
  servlet:
    context-path: /${system.name}

spring:
  datasource:
    url: jdbc:mysql://agno.top:3306/db_shortage_url?useUnicode=true&amp;characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: db_shortage_url
    password: wKFcneG2hKkKSMcb
    name: ${system.name}
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      validation-query: select 1

  redis:
    host: agno.top
    password: accessgnosis

#logging:
#  level: DEBUG
